title: Nicholas Handelman
email: nhandelman1@gmail.com
# > means to ignore newlines until baseurl:
description: > 
 Welcome to my GitHub Page. You are not free to look around... just kidding. Please contact me if you have any questions.

# baseurl: "/nhandelman1.github.io" the subpath of your site, e.g. /blog
# url: "" the base hostname & protocol for your site, e.g. http://example.com

# social links
facebook_username: nick.handelman
github_username:  nhandelman1
linkedin_username: nickhandelman
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: true
excerpt_separator: <!--endexcerpt-->

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - categories.html
 - education.md
 - experience.md
 - misc.md
 - skills.md
 - contact.md
 
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
